### ISSUE TITLE
Do you have archived patched r4i firmware?

### ISSUE THREAD

**Issue by jejer** [mid-kid/config#1]
Hi Mid kid,

Guess you are author of mkiddy.leerik.nl
I have a r4 clone card and want to try your patched firmware.

Appreciate if you can upload latest firmware and share the link, maybe "Patched V1.84.zip"

Thanks!
Sorry to contact you form this channel.

**Comment by mid-kid** [comment]
No problem. Unfortunately, I've lost most of what was hosted on mkiddy.leerik.nl. I've published the scraps I've been able to recover to: https://mid-kid.root.sx/R4i
Can you tell me where you found this? Might want to update the link there.

**Comment by jejer** [comment]
Thanks!
Found your site from gbatemp: https://gbatemp.net/threads/patched-r4i-sdhc-software-v1-84-for-r4isdhc.456771/
I send you a PM in gbatemp , later I realized you didn't login gbatemp from last year.
